# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: John Cho
title: M.S. in Computer Science at NYU; Graduating May 2026
email: hc4338@nyu.edu
phone: (929) 707-0751

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  donburi82
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: h00n-cho
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-regular fa-file
  url: https://drive.google.com/file/d/1kC2eyaDb898p3J5VV8B0NyVF_e2k12dp/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Welcome to my personal website. Here I share projects that don’t fit on a one-page resume, ranging from early proof-of-concepts to work that has evolved into longer-term projects, along with a few notes on what I enjoy outside of coding. I’m motivated by building technology that solves real-world problems.

  I’m currently seeking a new-grad Software Engineer or Machine Learning Engineer role in the United States. I prioritize team culture, mission, and the opportunity to learn and build meaningful products.

content:
  - title: Projects (that can be shared right now) # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Haruna
        link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        link_text: Report
        additional_links:
          - title:  GitHub page for project
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
        quote: >
          Python (Pandas, NumPy, Matplotlib, Yahoo Finance)
        description: | # this will include new lines to allow paragraphs
          - Led and presented a project on outperforming the S&P 500 through momentum trading and weight rebalancing
          - Streamlined model training and testing with Python (Pandas, NumPy, Matplotlib, Yahoo Finance) and achieved an average outperformance of 1.827 in annualized Sharpe Ratio on the test dataset
      - layout: top-middle
        title: Bloom
        link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        link_text: Report
        # additional_links:
        #   - title:  GitHub page for project
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        quote: >
          Python (Pandas, NumPy, Matplotlib, Yahoo Finance)
        description: | # this will include new lines to allow paragraphs
          - Led and presented a project on outperforming the S&P 500 through momentum trading and weight rebalancing
          - Streamlined model training and testing with Python (Pandas, NumPy, Matplotlib, Yahoo Finance) and achieved an average outperformance of 1.827 in annualized Sharpe Ratio on the test dataset
      - layout: top-middle
        title: Florise
        link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        link_text: Report
        # additional_links:
        #   - title:  GitHub page for project
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        quote: >
          Python (Pandas, NumPy, Matplotlib, Yahoo Finance)
        description: | # this will include new lines to allow paragraphs
          - Led and presented a project on outperforming the S&P 500 through momentum trading and weight rebalancing
          - Streamlined model training and testing with Python (Pandas, NumPy, Matplotlib, Yahoo Finance) and achieved an average outperformance of 1.827 in annualized Sharpe Ratio on the test dataset
      - layout: top-middle
        title: TravSum
        link: https://www.linkedin.com/posts/hkustkriss_kriss-quant-team-fall-202324-report-vol-activity-7156470854543974400-F-76?utm_source=share&utm_medium=member_desktop
        link_text: Report
        # additional_links:
        #   - title:  GitHub page for project
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        quote: >
          Python (Pandas, NumPy, Matplotlib, Yahoo Finance)
        description: | # this will include new lines to allow paragraphs
          - Led and presented a project on outperforming the S&P 500 through momentum trading and weight rebalancing
          - Streamlined model training and testing with Python (Pandas, NumPy, Matplotlib, Yahoo Finance) and achieved an average outperformance of 1.827 in annualized Sharpe Ratio on the test dataset

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I’m not coding, you’ll usually find me doing one of these:
      - Playing the [piano](https://www.google.com/)
      - Playing squash
      - Watching films
      - Reading (new habit)

# Footer
footer_show_references: true
# references_title:  (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
